### ISSUE TITLE
no warning's in project

### ISSUE THREAD

**Issue by khadmitriy** [xxpxxxxp/intellij-plugin-golangci-lint#85] opened 2021-08-18 11:56 UTC
Hello. After reinstalling ubuntu on 21.04 and golang on 1.17 - go lint stopped working.
I do not understand why, I did everything as in the manual, but it does not help

My go env
![image](https://user-images.githubusercontent.com/89138095/129893825-2ebc0f22-5bee-427e-b354-ffe4b27ac8ff.png)

I have go.mod file
![image](https://user-images.githubusercontent.com/89138095/129892498-7933461e-e517-4cd3-8b2d-5be0d80fee74.png)

My GOROOT
![image](https://user-images.githubusercontent.com/89138095/129892582-8a51ce00-1f80-4920-83b6-599f5d782a6d.png)

My GOPATH
![image](https://user-images.githubusercontent.com/89138095/129892638-4a41f48b-8c5d-4fa3-af46-334b6a1003cd.png)

Plugin installed
![image](https://user-images.githubusercontent.com/89138095/129892700-372584f4-c1f7-4ebd-9298-ad79fb367a19.png)

Plugin settings
![image](https://user-images.githubusercontent.com/89138095/129893002-ef9ecd15-7bb5-4052-a6d4-edfc0aa70873.png)

No error's in project, i can successfully build project 
![image](https://user-images.githubusercontent.com/89138095/129893202-7890553d-90d7-4b96-8cf0-b3fa6d03bd22.png)

But there are no warnings in the project (I know that I had them earlier in this project, and I see what was shown earlier)

I tried reinstall Goland, plugin and golang - but this don't help

**Comment by xxpxxxxp** [comment] 2021-08-18 16:13
Hi @khadmitriy , thanks for the very detailed infos! Meanwhile I still need Goland log to understand what happened. You can find Goland log by menu `Help` - `Show Log in xxx`,  then search for `go-linter` in the log.

**Comment by khadmitriy** [comment] 2021-08-19 04:38
After starting a new IDE session, I only found 1 log (linter still not working) 

2021-08-19 09:34:51,130 [      0]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE STARTED ------------------------------------------------------ 
 2021-08-19 09:35:11,228 [  20098]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: Go Linter (1.5.4) 

I tried restarting IDE to get more logs (linter still not working) 

2021-08-19 09:47:48,610 [      0]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE STARTED ------------------------------------------------------ 
2021-08-19 09:47:49,947 [   1337]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: Go Linter (1.5.4) 

and i have only this log again

I will give you all the logs I found by requesting "go linter" in the log file, maybe this will help 

2021-08-18 17:50:27,218 [1539157]   WARN - tions.ex.ConfigurableCardPanel - auto-dispose 'Go Linter' id=preference.GoLinterConfigurable 
2021-08-18 17:18:38,538 [ 563287]   INFO -                      go-linter - Cannot get confirmation from dispatch thread, break the loop 
2021-08-18 17:18:39,295 [ 564044]   WARN - tions.ex.ConfigurableCardPanel - auto-dispose 'Go Linter' id=preference.GoLinterConfigurable 

these were all logs, and you may need this information 

2021-08-19 09:47:48,667 [     57]   INFO -        #com.intellij.idea.Main - IDE: GoLand (build #GO-212.4746.93, 27 Jul 2021 12:45) 
2021-08-19 09:47:48,668 [     58]   INFO -        #com.intellij.idea.Main - OS: Linux (5.11.0-31-generic, amd64) 
2021-08-19 09:47:48,688 [     78]   INFO -        #com.intellij.idea.Main - JRE: 11.0.11+9-b1504.13 (JetBrains s.r.o.) 
2021-08-19 09:47:48,689 [     79]   INFO -        #com.intellij.idea.Main - JVM: 11.0.11+9-b1504.13 (OpenJDK 64-Bit Server VM) 

![image](https://user-images.githubusercontent.com/89138095/130005587-34d5345a-d826-40dc-8cd6-7f392dfef58e.png)

![image](https://user-images.githubusercontent.com/89138095/130005610-2dc43e46-765d-4dc2-bc9d-68fa0687d72d.png)

![image](https://user-images.githubusercontent.com/89138095/130006813-baa8c7b5-54b6-4885-8ca2-cb0686da966d.png)

an example, there should have been 2 warnings, global variable and package named with a capital letter, but, have no

**Comment by xxpxxxxp** [comment] 2021-08-19 13:51
Thanks @khadmitriy , seems the plugin didn't run at all, please try `Code` - `Inspect Code`, choose file scope. If there's no lint, then search `go-linter` in the Goland log.

**Comment by khadmitriy** [comment] 2021-08-20 05:34
![image](https://user-images.githubusercontent.com/89138095/130183901-73c07e97-7727-439e-b0d4-96a4c60f21f6.png)

![image](https://user-images.githubusercontent.com/89138095/130183946-edaf3fbc-c80a-405e-a37c-5decc98bdc10.png)

done, but there are no linter logs in the file again. Only

2021-08-20 11:21:06,375 [  17617]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: Go Linter (1.5.4) 

but i found many ide errors, maybe this will help 

2021-08-20 11:23:13,837 [ 145079]   INFO - ex.GlobalInspectionContextBase - Code inspection started 
2021-08-20 11:23:13,963 [ 145205]   INFO - ex.GlobalInspectionContextImpl - Code inspection finished. Took 106 ms 
2021-08-20 11:24:32,410 [ 223652]   INFO - ex.GlobalInspectionContextBase - Code inspection started 
2021-08-20 11:24:32,512 [ 223754]   INFO - ex.GlobalInspectionContextImpl - Code inspection finished. Took 97 ms 
2021-08-20 11:24:47,544 [ 238786]   INFO - ex.GlobalInspectionContextBase - Code inspection started 
2021-08-20 11:24:47,758 [ 239000]   WARN - api.actionSystem.ex.ActionUtil - Can not find action by id CompileDirty 
2021-08-20 11:24:47,791 [ 239033]   WARN - nSystem.impl.ActionToolbarImpl - 'CodeInspection' toolbar by default uses any focused component to update its actions. Toolbar actions that need local UI context would be incorrectly disabled. Please call toolbar.setTargetComponent() explicitly. 
java.lang.Throwable: toolbar creation trace
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.<init>(ActionToolbarImpl.java:112)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.createActionToolbar(ActionManagerImpl.java:438)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.createActionToolbar(ActionManagerImpl.java:432)
	at com.intellij.codeInspection.ui.InspectionResultsView.createToolbar(InspectionResultsView.java:268)
	at com.intellij.codeInspection.ui.InspectionResultsView.createLeftActionsToolbar(InspectionResultsView.java:232)
	at com.intellij.codeInspection.ui.InspectionResultsView.createActionsToolbar(InspectionResultsView.java:205)
	at com.intellij.codeInspection.ui.InspectionResultsView.<init>(InspectionResultsView.java:170)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.lambda$initializeViewIfNeeded$20(GlobalInspectionContextImpl.java:696)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:887)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:488)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2021-08-20 11:24:47,809 [ 239051]   WARN - nSystem.impl.ActionToolbarImpl - 'CodeInspection' toolbar by default uses any focused component to update its actions. Toolbar actions that need local UI context would be incorrectly disabled. Please call toolbar.setTargetComponent() explicitly. 
java.lang.Throwable: toolbar creation trace
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.<init>(ActionToolbarImpl.java:112)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.createActionToolbar(ActionManagerImpl.java:438)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.createActionToolbar(ActionManagerImpl.java:432)
	at com.intellij.codeInspection.ui.InspectionResultsView.createToolbar(InspectionResultsView.java:268)
	at com.intellij.codeInspection.ui.InspectionResultsView.createRightActionsToolbar(InspectionResultsView.java:218)
	at com.intellij.codeInspection.ui.InspectionResultsView.createActionsToolbar(InspectionResultsView.java:206)
	at com.intellij.codeInspection.ui.InspectionResultsView.<init>(InspectionResultsView.java:170)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.lambda$initializeViewIfNeeded$20(GlobalInspectionContextImpl.java:696)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:887)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:488)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2021-08-20 11:24:52,786 [ 244028]   INFO - ex.GlobalInspectionContextImpl - Code inspection finished. Took 5237 ms 
2021-08-20 11:25:13,138 [ 264380]   INFO - ex.GlobalInspectionContextBase - Code inspection started 
2021-08-20 11:25:13,245 [ 264487]   INFO - ex.GlobalInspectionContextImpl - Code inspection finished. Took 101 ms 
2021-08-20 11:25:13,486 [ 264728]   INFO - rationStore.ComponentStoreImpl - Saving appGeneralSettings took 12 ms 
2021-08-20 11:25:55,938 [ 307180]   INFO - ex.GlobalInspectionContextBase - Code inspection started 
2021-08-20 11:25:56,054 [ 307296]   INFO - ex.GlobalInspectionContextImpl - Code inspection finished. Took 111 ms 
2021-08-20 11:27:07,794 [ 379036]   INFO - rationStore.ComponentStoreImpl - Saving appGeneralSettings took 14 ms 
2021-08-20 11:28:00,650 [ 431892]   INFO - j.ide.actions.RevealFileAction - Timed out 
2021-08-20 11:28:00,651 [ 431893]   INFO - j.ide.actions.RevealFileAction - Nautilus-Share-Message: 11:27:51.009: Called "net usershare info" but it failed: Failed to execute child process “net” (No such file or directory)
 
2021-08-20 11:28:24,284 [ 455526]   INFO - j.ide.actions.RevealFileAction - Timed out 
2021-08-20 11:28:24,284 [ 455526]   INFO - j.ide.actions.RevealFileAction - Nautilus-Share-Message: 11:28:14.629: Called "net usershare info" but it failed: Failed to execute child process “net” (No such file or directory)

**Comment by xxpxxxxp** [comment] 2021-08-20 05:39
Seems the plugin never got a chance to run. I saw a guy post a similar question in Goland channel, would you mind try the same?

**Attention: please export settings before restoring default!**

![image](https://user-images.githubusercontent.com/1585918/130184956-fc3efd6b-67bc-4232-a648-8973bf1d9b1f.png)

**Comment by khadmitriy** [comment] 2021-08-20 08:50
Didn't help. After installing the plugin, it doesn't work again. In the log's I only found this.

2021-08-20 14:40:19,313 [ 168291]   WARN - tions.ex.ConfigurableCardPanel - auto-dispose 'Go Linter' id=preference.GoLinterConfigurable 

and this (again).
2021-08-20 14:42:08,008 [   1351]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: Go Linter (1.5.4) 

I tried to check incpect code -> file and check the log, but again there is nothing.

**Comment by xxpxxxxp** [comment] 2021-08-22 13:58
Would you mind try the IDE and plugin with https://github.com/gin-gonic/gin ? That would help me understand the case.

**Comment by khadmitriy** [comment] 2021-08-23 04:46
![image](https://user-images.githubusercontent.com/89138095/130390984-8100b360-5452-4043-bfd8-5b8d5f4f4a71.png)

![image](https://user-images.githubusercontent.com/89138095/130391044-cb429737-07bc-4383-a55c-0296ab724bb2.png)

![image](https://user-images.githubusercontent.com/89138095/130391121-15156402-60fb-4236-bf9e-050d7b83b103.png)

I found only 1 error, maybe the plugin somehow stopped working due to "typecheck"? 

![image](https://user-images.githubusercontent.com/89138095/130391246-2941ced4-1434-44c1-a124-fb8ab99ca67e.png)

**Comment by khadmitriy** [comment] 2021-08-24 05:40
![image](https://user-images.githubusercontent.com/89138095/130561495-5eec73b0-ef2e-4f8d-985a-13032b9b8d0a.png)

![image](https://user-images.githubusercontent.com/89138095/130561524-78c1c67f-25b0-453b-874e-c5e9a312b5c9.png)

only typecheck works, but after shutdown - still works (accepted configuration, reopened IDE) 

![image](https://user-images.githubusercontent.com/89138095/130561667-7d1a9974-a930-4e03-a0e8-11ae318593c7.png)

![image](https://user-images.githubusercontent.com/89138095/130561915-d0adb18f-36fa-466a-bf6d-a633b743e334.png)

**Comment by xxpxxxxp** [comment] 2021-08-24 09:31
Let me set up an Ubuntu VM this night and test it then. Meanwhile, would you copy-paste the content of
`~/.local/share/JetBrains/GoLand2021.2/options/other.xml`
I need properties that start with `go-` to apply exactly the same settings as yours.

**Comment by khadmitriy** [comment] 2021-08-25 04:44
![image](https://user-images.githubusercontent.com/89138095/130727615-a9d5eae3-f395-4cbe-95a0-236f88a2b408.png)

there is no this file

**Comment by xxpxxxxp** [comment] 2021-08-25 16:07
Sorry for the `gin` thing, I found they've merged a `.golangci.yml` at 8/19 and fixed most issues, only a few `typecheck` issues left. So what you've seen before is expected.
But that also means the plugin is working well with `gin`. So I'm guessing that your project is not using package management like `go mod`? Is it a pure Goland project? It's a known issue that the plugin doesn't work with pure Goland project. A quick workaround would be simply run command `go mod init <name>` under the project root.

**Comment by xxpxxxxp** [comment] 2021-08-28 15:06
Please push the toy project to Github so I can clone it from your repo.

**Comment by khadmitriy** [comment] 2021-08-30 08:22
Okay.

https://github.com/khadmitriy/project

go linter's work only in config.go and structs.go. In other packages linter's don't work.

**Comment by xxpxxxxp** [comment] 2021-08-30 08:23
Thanks a lot! I'll check it out this night.

**Comment by xxpxxxxp** [comment] 2021-08-31 03:33
Thanks, I was able to repro the bug now. There exist the same problem as #84 that caused by UTF8 characters (Russian, Chinese), and some others. I'll release a new version to address the issue soon.

**Comment by khadmitriy** [comment] 2021-08-31 03:54
Thanks for the plugin! I was thinking about Russian encoding in file name or package name, did I fix it everywhere in the project, or not? Or, if there is Russian encoding in the file (comments), can there be problems too?

**Comment by xxpxxxxp** [comment] 2021-08-31 05:59
There's no fix required on your side, Russian characters in filename, code or comments are all allowed. While in general, I guess it's not a good idea to have non-ASCII characters in filename.

**Comment by xxpxxxxp** [comment] 2021-08-31 14:43
I've fixed the UTF8 character issue, while there's still some issues seems related to `golangci-lint` itself.

I've run the exact same command under your project root
```golangci-lint run --out-format json --allow-parallel-runners -j 3 --max-issues-per-linter 0 --max-same-issues 0 --disable-all -E exportloopref,funlen,noctx,gocritic,gocognit,nestif,wsl,exhaustive,nilerr,revive,prealloc,staticcheck,exhaustivestruct,errorlint,gomnd,misspell,typecheck,gochecknoinits,rowserrcheck,thelper,tparallel,asciicheck,testpackage,nolintlint,gosec,goerr113,maligned,gomodguard,unused,godox,unconvert,depguard,paralleltest,gosimple,godot,goprintffuncname,gocyclo,predeclared,importas,cyclop,goconst,errcheck,forcetypeassert,sqlclosecheck,dogsled,ineffassign,deadcode,scopelint,unparam,goheader,structcheck,nakedret,promlinter,nlreturn,durationcheck,gochecknoglobals,interfacer,govet,dupl,forbidigo,gomoddirectives,tagliatelle,wrapcheck,wastedassign,lll,makezero,varcheck,bodyclose,golint,stylecheck,whitespace,ifshort applicationstate```

Under Windows it gives correct lints, under Ubuntu 21.04 + Go 1.17 it only gives `typecheck` lint, which I understand is kind of compilation failure. I'm wondering if the command works in your env.

I've seen an issue https://github.com/golangci/golangci-lint/issues/2195 discuss a quite similar situation. If the command not working for you too, let's escalate it to `golangci-lint` maintainers.

**Comment by heyanlong** [comment] 2021-09-01 03:53
I also encountered the some problem.
System: macOS
GoLand: 2021.2.1
Golang: 1.7

**Comment by khadmitriy** [comment] 2021-09-01 05:19
Yes, only typecheck works, the command didn't help for other lints.

**Comment by xxpxxxxp** [comment] 2021-09-02 03:17
Hi @khadmitriy , I'd like to open an issue to https://github.com/golangci/golangci-lint/issues , while seems you have destroyed this repo https://github.com/khadmitriy/project . Any chance you can push it back? I need it to help them reproduct the problem easier.

**Comment by khadmitriy** [comment] 2021-09-02 04:50
I thought that he would no longer be needed, sorry, I returned the repository.

https://github.com/khadmitriy/project

**Comment by xxpxxxxp** [comment] 2021-09-02 08:41
Hi @heyanlong , I've tested on macOS with Go 1.17 + golangci-lint 1.42.0 with no such problem. The problem seems only exist on Linux, not Windows or macOS. If the issue still persists, please open another issue with details, thanks.

**Comment by xxpxxxxp** [comment] 2021-09-03 06:49
@khadmitriy I've got a clue that build `golangci-lint` from source with Go 1.17 would resolve the issue, I'll try it out tommorrow.

**Comment by khadmitriy** [comment] 2021-09-03 08:14
Good

**Comment by xxpxxxxp** [comment] 2021-09-04 05:27
Hi @khadmitriy , it works! Please execute command `go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.0` to compile `golangci-lint` from source with Go 1.17 (pre-request: make sure `gcc` is installed, if not run `sudo apt install gcc`)

Then open executable `$GOPATH/bin/golangci-lint` in plugin settings, works perfectly inside IDE.

**Comment by khadmitriy** [comment] 2021-09-06 04:22
Yes, it works, thanks!

**Comment by xxpxxxxp** [comment] 2021-09-06 04:25
Great! The repo is no longer needed, feel free to delete it now.

**Closed by xxpxxxxp** 2021-09-06 04:25 UTC

**Comment by xxpxxxxp** [comment] 2021-09-07 02:53
Hi @khadmitriy , a quick reminder, `golangci-lint` released a new version to fix this https://github.com/golangci/golangci-lint/releases/tag/v1.42.1 , you can get rid of self-build binary now.
