### ISSUE TITLE
Error - can't get enabled linters: unknown linters: 'perfsprint,protogetter'

### ISSUE THREAD

**Issue by oleksiy-os** [xxpxxxxp/intellij-plugin-golangci-lint#156] opened 2024-01-19 12:09 UTC
The error appears in settings->tools->Go Linter

This issue appeared after new linters in golangci v 1.55
Here is list of all new linters https://golangci-lint.run/usage/linters/

<img width="1728" alt="image" src="https://github.com/xxpxxxxp/intellij-plugin-golangci-lint/assets/30931808/127b9a8b-0226-4b22-a9db-69719105513d">

Thanks a lot for your work.

**Comment by xxpxxxxp** [comment] 2024-01-19 17:53
HI @oleksiy-os , I tested it with a fresh new project with no problem. I suspect it's related to your local `.golangci.yml` config file, would you confirm if there is such a config file? And paste the content here if possible.

**Comment by xxpxxxxp** [comment] 2024-01-23 18:48
Hi @oleksiy-os I hope you well! I'll close this and hope the plugin works again. If not, feel free to reopen this.

**Comment by xxpxxxxp** [comment] 2024-01-26 06:22
no worries! I've tested with .golangci.yml above, but cannot reproduce the bug yet. Could you let me know if it's still for you? Also, does the plugin work in such case, showing correct hints in the editor besides the config problem?

**Comment by oleksiy-os** [comment] 2024-01-29 08:57
The problem is still there. Plugin doesn't work in such case.


Would be nice just skip some linters if plugin doesn't know them or gets err.

**Comment by oleksiy-os** [comment] 2024-02-06 10:58
I'm using binary from https://golangci-lint.run/usage/install/#binaries
macOS - yes

But seems only I have such issue so not a problem. Probably you can close the issue :)

Thanks for try

**Comment by xxpxxxxp** [comment] 2024-02-06 18:21
I have a conjecture, those 2 not found linters are first introduced into golangci-lint from v1.55.0, if you are using a binary prior, with those 2 enabled in config file, the error will show up. Please try download and apply the latest binary, it should resolve the issue.

**Closed by xxpxxxxp** 2024-02-06 18:21 UTC

**Comment by xxpxxxxp** [comment] 2024-02-06 21:11
Then one last thing to confirm, check whether the golangci-lint binary set in the plugin config is the 1.55.2 one.
Since there's exception on plugin panel, you can find the config in <Project Root Directory>/.idea/golinter.xml

**Comment by oleksiy-os** [comment] 2024-02-08 11:04
ohh... You are right! I have 2 golang-ci binaries in os... The right and latest on the users folder go/bin (default install from golangci) and old one in the path default for golang /usr/local/bin .... So goland takes wrong binary

Thanks a lot. Sorry for my fault :)

**Comment by xxpxxxxp** [comment] 2024-02-08 18:07
So glad you fix it, have a good day!
