### ISSUE TITLE
Can't lint when using build tags

### ISSUE THREAD

**Issue by fiunchinho** [xxpxxxxp/intellij-plugin-golangci-lint#15] opened 2020-04-09 09:36 UTC
Hey!

It seems it can't lint files with custom build constraints.
```
2020-04-09 11:32:05,795 [83853019]   WARN -                      go-linter - Run error: level=warning msg="[runner] Can't run linter goanalysis_metalinter: deadcode: analysis skipped: errors in package: [-: build constraints exclude all Go files in /.......]"
```

I have the build tags configured in Intellij, so everything else works fine. So I guess the linter is not taking that into consideration

![image](https://user-images.githubusercontent.com/627038/78880945-68aa7880-7a56-11ea-8860-c16597daca96.png)

**Comment by xxpxxxxp** [comment] 2020-04-09 09:46
Thanks @fiunchinho ! It is indeed not considered now. Would you please try with enable custom options with "--build-tags k8srequired" as a workaround?
![image](https://user-images.githubusercontent.com/1585918/78881931-09665b80-7a8a-11ea-9ffa-3375457c0846.png)

**Comment by fiunchinho** [comment] 2020-04-09 10:25
Same errors :/

**Comment by xxpxxxxp** [comment] 2020-04-09 16:05
@fiunchinho I found the silly mistake I've made. Custom Options is actually not working now, I'll make it right soon.

**Comment by xxpxxxxp** [comment] 2020-04-09 17:23
I've pushed commits to fix this and issue before, ETA to release v1.3.2 in 2 days.

**Comment by fiunchinho** [comment] 2020-04-09 18:54
That sounds awesome. Thanks!

**Comment by xxpxxxxp** [comment] 2020-04-10 12:59
@fiunchinho Now the new version is available, please help me check if those 2 issues been resolved, thanks.

**Comment by fiunchinho** [comment] 2020-04-10 13:29
New error

```
2020-04-10 15:27:21,336 [ 116159]   WARN -                      go-linter - Run error: level=warning msg="Failed to discover go env: failed to run 'go env': exit status 2"
level=error msg="Running error: context loading failed: failed to load program with go/packages: could not parse GOARCH and Go compiler in format \"<GOARCH> <compiler>\" from stdout of go command:\nGOROOT= GOPATH=/home/jose/dev:null GO111MODULE= PWD=/home/jose go [list -f {{context.GOARCH}} {{context.Compiler}} -tags k8srequired -- unsafe]\ndir: /home/jose/dev/src/github.com/giantswarm/azure-operator/integration/setup\nstdout: <<>>\nstderr: <<go: GOPATH entry is relative; must be absolute path: \"null\".\nFor more details see: 'go help gopath'\n>>"
. Usually it's caused by wrongly configured parameters or corrupted with config file. 
2020-04-10 15:27:21,337 [ 116160]   WARN -                      go-linter - Debug command: cd /home/jose/dev/src/github.com/giantswarm/azure-operator/integration/setup && export PATH=/usr/lib/go-1.13/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin && export GOPATH=/home/jose/dev:null && /usr/local/bin/golangci-lint run --out-format json --build-tags k8srequired --concurrency 2 --max-issues-per-linter 0 --max-same-issues 0 --maligned.suggest-new --disable-all -E deadcode,errcheck,gosimple,govet,ineffassign,staticcheck,structcheck,unused,varcheck . 
```

**Comment by xxpxxxxp** [comment] 2020-04-10 13:56
Thanks a lot @fiunchinho ! You are very helpful, v1.3.2 is recalled from repo because of this regression. The bug is an easy fix, a new release will soon be available.

**Comment by xxpxxxxp** [comment] 2020-04-13 06:32
@fiunchinho would you please confirm if the issue still presents now?

**Comment by fiunchinho** [comment] 2020-04-13 09:41
it seems to be working fine! Just awesome, thanks!!

**Comment by xxpxxxxp** [comment] 2020-04-13 09:46
Thanks! I'll close the issue then.

**Closed** 2020-04-13 09:46 UTC
